"""Minimal Isolation Forest anomaly scorer for Blue host observations.

This module intentionally operates only on the existing Blue-visible host vector
from blue_obs_features.py. It never consumes privileged simulator state,
compromise labels, action results, or rewards.
"""

from __future__ import annotations

import pickle
from pathlib import Path
from typing import Iterable

import numpy as np
from sklearn.ensemble import IsolationForest


class IsolationForestAnomalyScorer:
    """Fit a clean-data Isolation Forest and emit normalized host anomaly scores.

    The model consumes one host feature vector or a batch of host feature vectors:
    shape (feature_dim,) or (n_samples, feature_dim). The score is normalized to
    the stable range [0, 1], where larger values denote more anomalous input.
    """

    def __init__(self, *, n_estimators=200, contamination="auto",
                 random_state=0, feature_dim=None):
        self.model = IsolationForest(
            n_estimators=n_estimators,
            contamination=contamination,
            random_state=random_state,
        )
        self._is_fitted = False
        self._feature_dim = feature_dim
        self._score_min = 0.0
        self._score_max = 1.0

    @staticmethod
    def collect_clean_reset_matrix(*, agent="blue_agent_0", seeds=range(25),
                                  steps=300):
        """Collect the repository's clean reset-host matrix used for IF training.

        This intentionally mirrors the clean-data methodology already used by
        blue_iforest_experiment.py without training automatically during env
        resets or step execution.
        """
        from CybORG import CybORG
        from CybORG.Agents import DiscoveryFSRed, EnterpriseGreenAgent, SleepAgent
        from CybORG.Simulator.Scenarios import EnterpriseScenarioGenerator
        from blue_obs_features import obs_to_matrix

        clean_vecs = []
        for seed in seeds:
            scenario = EnterpriseScenarioGenerator(
                blue_agent_class=SleepAgent,
                green_agent_class=EnterpriseGreenAgent,
                red_agent_class=DiscoveryFSRed,
                steps=steps,
            )
            cyborg = CybORG(scenario_generator=scenario, seed=seed)
            result = cyborg.reset(agent=agent)
            _, mat = obs_to_matrix(result.observation, agent)
            clean_vecs.extend(mat)

        X_clean = np.asarray(clean_vecs, dtype=np.float32)
        if X_clean.size == 0:
            raise ValueError("no clean host vectors were collected")
        return X_clean

    @staticmethod
    def summarize_matrix(X):
        """Return diversity metadata for a host-vector matrix."""
        arr = np.asarray(X, dtype=np.float32)
        if arr.ndim != 2:
            raise ValueError("X must be a 2D host-vector matrix")
        if arr.shape[0] == 0:
            raise ValueError("no host vectors were collected")
        unique_rows, counts = np.unique(arr, axis=0, return_counts=True)
        dominant_pct = float(np.max(counts) / arr.shape[0] * 100.0)
        stats = {
            "n_samples": int(arr.shape[0]),
            "n_unique_vectors": int(unique_rows.shape[0]),
            "dominant_vector_pct": dominant_pct,
            "feature_unique_values": [int(np.unique(arr[:, i]).size)
                                      for i in range(arr.shape[1])],
            "feature_min": [float(arr[:, i].min()) for i in range(arr.shape[1])],
            "feature_max": [float(arr[:, i].max()) for i in range(arr.shape[1])],
            "feature_std": [float(arr[:, i].std()) for i in range(arr.shape[1])],
            "nan_inf": bool(np.any(~np.isfinite(arr))),
            "top_vectors": [
                {"vector": [float(value) for value in row.tolist()],
                 "count": int(count)}
                for row, count in sorted(zip(unique_rows, counts),
                                         key=lambda item: item[1],
                                         reverse=True)[:5]
            ],
        }
        return stats

    @staticmethod
    def collect_benign_matrix(*, seeds=range(8), steps=60, monitor_every=2,
                             blue_agents=None):
        """Collect a larger benign Blue-visible host dataset without attack labels.

        The data is generated by legitimate Green-user activity on the scenario
        hosts, with `fp_detection_rate` raised to produce observable process and
        connection events while `phishing_error_rate` is held at zero so no
        attack sessions are injected. Blue Monitor is used to harvest those
        benign, Blue-visible events from each host. The result stays offline and
        explicit: it is never used to train the runtime model automatically.
        """
        if blue_agents is None:
            blue_agents = tuple(f"blue_agent_{i}" for i in range(5))
        blue_agents = tuple(blue_agents)
        if not blue_agents:
            raise ValueError("at least one Blue agent must be collected")

        from CybORG import CybORG
        from CybORG.Agents import EnterpriseGreenAgent, SleepAgent
        from CybORG.Simulator.Actions import Sleep
        from CybORG.Simulator.Actions.AbstractActions import Monitor
        from CybORG.Simulator.Scenarios import EnterpriseScenarioGenerator
        from blue_obs_features import obs_to_matrix

        clean_vecs = []
        for seed in seeds:
            scenario = EnterpriseScenarioGenerator(
                blue_agent_class=SleepAgent,
                green_agent_class=EnterpriseGreenAgent,
                red_agent_class=SleepAgent,
                steps=steps,
            )
            cyborg = CybORG(scenario_generator=scenario, seed=seed)
            cyborg.reset(agent="blue_agent_0")
            for name, iface in cyborg.environment_controller.agent_interfaces.items():
                if "green_agent" not in name or getattr(iface, "agent", None) is None:
                    continue
                host = cyborg.environment_controller.state.sessions[name][0].hostname
                iface.agent.own_ip = (
                    cyborg.environment_controller.state.hosts[host].interfaces[0].ip_address
                )
                iface.agent.fp_detection_rate = 1.0
                iface.agent.phishing_error_rate = 0.0
            for tick in range(steps):
                actions = {
                    agent: Monitor(session=0, agent=agent)
                    if (tick + 1) % monitor_every == 0 else Sleep()
                    for agent in blue_agents
                }
                cyborg.parallel_step(actions=actions)
                for agent in blue_agents:
                    obs = cyborg.get_observation(agent)
                    _, mat = obs_to_matrix(obs, agent)
                    clean_vecs.extend(mat)

        X_clean = np.asarray(clean_vecs, dtype=np.float32)
        if X_clean.size == 0:
            raise ValueError("no benign host vectors were collected")
        stats = IsolationForestAnomalyScorer.summarize_matrix(X_clean)
        stats.update({
            "seeds": list(seeds),
            "steps": int(steps),
            "monitor_every": int(monitor_every),
            "blue_agents": list(blue_agents),
            "behavior": "benign Green activity (fp_detection_rate=1.0, phishing_error_rate=0.0) + Blue Monitor",
        })
        return X_clean, stats

    @classmethod
    def fit_clean_reset_collection(cls, *, agent="blue_agent_0",
                                  seeds=range(25), steps=300):
        """Build the repo's clean reset dataset and fit a scorer on it."""
        scorer = cls(random_state=0)
        X_clean = cls.collect_clean_reset_matrix(agent=agent, seeds=seeds,
                                                steps=steps)
        scorer.fit(X_clean)
        return scorer

    @classmethod
    def fit_benign_collection(cls, *, seeds=range(8), steps=60,
                             monitor_every=2, blue_agents=None):
        """Build a richer explicit benign dataset and fit a scorer on it."""
        scorer = cls(random_state=0)
        X_clean, _ = cls.collect_benign_matrix(seeds=seeds, steps=steps,
                                               monitor_every=monitor_every,
                                               blue_agents=blue_agents)
        scorer.fit(X_clean)
        return scorer

    @property
    def is_fitted(self):
        return self._is_fitted

    @staticmethod
    def _coerce_matrix(X):
        arr = np.asarray(X, dtype=np.float32)
        if arr.ndim == 1:
            arr = arr.reshape(1, -1)
        if arr.ndim != 2:
            raise ValueError("X must be a 1D vector or a 2D array")
        if arr.shape[1] == 0:
            raise ValueError("feature vectors must have at least one dimension")
        return arr

    def fit(self, X):
        arr = self._coerce_matrix(X)
        if self._feature_dim is None:
            self._feature_dim = arr.shape[1]
        elif arr.shape[1] != self._feature_dim:
            raise ValueError(
                f"expected feature dimension {self._feature_dim}, got {arr.shape[1]}"
            )
        self.model = IsolationForest(random_state=0)
        self.model.fit(arr)
        self._is_fitted = True
        raw = -self.model.decision_function(arr)
        finite = np.isfinite(raw)
        if not np.any(finite):
            self._score_min = 0.0
            self._score_max = 1.0
            return self
        raw = raw[finite]
        self._score_min = float(np.min(raw))
        self._score_max = float(np.max(raw))
        if not np.isfinite(self._score_min) or not np.isfinite(self._score_max):
            self._score_min = 0.0
            self._score_max = 1.0
        if self._score_max - self._score_min < 1e-12:
            self._score_max = self._score_min + 1.0
        return self

    def _normalize(self, raw):
        raw = np.asarray(raw, dtype=np.float32)
        if not self._is_fitted:
            return np.clip(np.full(raw.shape, 0.5, dtype=np.float32), 0.0, 1.0)
        scaled = (raw - self._score_min) / (self._score_max - self._score_min)
        return np.clip(scaled, 0.0, 1.0).astype(np.float32)

    def score_vector(self, x):
        arr = self._coerce_matrix(x)
        if arr.shape[0] != 1:
            raise ValueError("score_vector expects a single host vector")
        if self._feature_dim is not None and arr.shape[1] != self._feature_dim:
            raise ValueError(
                f"expected feature dimension {self._feature_dim}, got {arr.shape[1]}"
            )
        if not self._is_fitted:
            return 0.5
        raw = -self.model.decision_function(arr)[0]
        return float(self._normalize(np.asarray([raw], dtype=np.float32))[0])

    def score_batch(self, X):
        arr = self._coerce_matrix(X)
        if self._feature_dim is not None and arr.shape[1] != self._feature_dim:
            raise ValueError(
                f"expected feature dimension {self._feature_dim}, got {arr.shape[1]}"
            )
        if not self._is_fitted:
            return np.full(arr.shape[0], 0.5, dtype=np.float32)
        raw = -self.model.decision_function(arr)
        return self._normalize(raw).astype(np.float32)

    def save(self, model_path):
        path = Path(model_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("wb") as stream:
            pickle.dump(self, stream)
        return path

    @classmethod
    def load(cls, model_path):
        with Path(model_path).open("rb") as stream:
            obj = pickle.load(stream)
        if not isinstance(obj, cls):
            raise TypeError("loaded object is not an IsolationForestAnomalyScorer")
        return obj


__all__ = ["IsolationForestAnomalyScorer"]
